修复chrome浏览器bug导致的上传图片的时候速度奇慢的问题
teambition/simditor pull request #3
Opened 2017-02-15 06:14 UTC by VeraWei

2017-02-15 08:32 UTC, Brooooooklyn commented
测试过吗

2017-02-15 08:36 UTC, VeraWei commented
@Brooooooklyn 没有，没装测试环境。。。

2017-02-15 08:36 UTC, Brooooooklyn commented
那我帮你测一下吧

2017-02-15 08:37 UTC, VeraWei commented
鼓掌，撒花

2017-02-16 10:06 UTC, Brooooooklyn requested changes

2017-02-16 10:06 UTC, Brooooooklyn commented on lib/simditor.js
> +          accept: 'image/gif, image/png, image/jpeg, image/bmp, image/webp'
只有这几种是不是不够全面，我觉得全加上比较合适
http://www.altools.com/altools/alsee/features/view-23-image-formats.aspx

2017-02-17 02:52 UTC, VeraWei commented on lib/simditor.js
> +          accept: 'image/gif, image/png, image/jpeg, image/bmp, image/webp'
已经加上了，你看下

2017-02-17 03:03 UTC, Brooooooklyn requested changes

2017-02-17 03:03 UTC, Brooooooklyn commented on lib/simditor.js
> +    acceptImageType = ['ANI', 'BMP', 'CAL', 'FAX', 'GIF', 'IMG', 'JBG', 'JPE', 'JPEG', 'JPG', 'MAC', 'PBM', 'PCD', 'PCX', 'PCT', 'PGM', 'PNG', 'PPM', 'PSD', 'RAS', 'TGA', 'TIFF', 'WMF'];
用 map 啊。。。
acceptImageType = ['xxx'].map(v => 'image/' + v)

2017-02-17 05:50 UTC, nekolab commented on lib/simditor.js
> +    acceptImageType = ['ANI', 'BMP', 'CAL', 'FAX', 'GIF', 'IMG', 'JBG', 'JPE', 'JPEG', 'JPG', 'MAC', 'PBM', 'PCD', 'PCX', 'PCT', 'PGM', 'PNG', 'PPM', 'PSD', 'RAS', 'TGA', 'TIFF', 'WMF'];
这些格式服务端很多都不支持。。真的有必要加上去么。。。

2017-02-17 05:51 UTC, VeraWei commented on lib/simditor.js
> +    acceptImageType = ['ANI', 'BMP', 'CAL', 'FAX', 'GIF', 'IMG', 'JBG', 'JPE', 'JPEG', 'JPG', 'MAC', 'PBM', 'PCD', 'PCX', 'PCT', 'PGM', 'PNG', 'PPM', 'PSD', 'RAS', 'TGA', 'TIFF', 'WMF'];
换成map了

2017-02-17 05:51 UTC, VeraWei commented on lib/simditor.js
> +          accept: acceptImageType.map(type(function() {
但感觉这个coffee语法翻译出来的有点奇怪，虽然数据是对的 :>>>

2017-02-17 05:52 UTC, VeraWei commented on lib/simditor.js
> +    acceptImageType = ['ANI', 'BMP', 'CAL', 'FAX', 'GIF', 'IMG', 'JBG', 'JPE', 'JPEG', 'JPG', 'MAC', 'PBM', 'PCD', 'PCX', 'PCT', 'PGM', 'PNG', 'PPM', 'PSD', 'RAS', 'TGA', 'TIFF', 'WMF'];
加上总是没错的

2017-02-17 06:03 UTC, Brooooooklyn approved these changes

2017-02-17 13:59 UTC, nekolab commented on src/buttons/image.coffee
> +        accept: acceptImageType.map(type => 'image/' + type).join()
这么写 `acceptImageType.map((type) -> 'image/' + type).join()`

2017-02-20 02:01 UTC, VeraWei commented on src/buttons/image.coffee
> +        accept: acceptImageType.map(type => 'image/' + type).join()
是可以这样写，但这和coffee语法 不需要加括号又冲突了, 不纠结不改了，都是对的 :(

2017-02-20 02:14 UTC, Brooooooklyn requested changes

2017-02-20 02:14 UTC, Brooooooklyn commented on src/buttons/image.coffee
> +        accept: acceptImageType.map(type => 'image/' + type).join()
`acceptImageType.map((type) -> 'image/' + type).join()` 正解

2017-02-20 02:20 UTC, Brooooooklyn approved these changes

2017-02-20 02:20 UTC, merged